
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'

import Header from "../components/Header/Header";
import Nav from "../components/Nav/Nav"
import Contents from "../components/Contents/Contents"


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Isaiah's Blog",
  description: "Generated by create next app",
  icons: {
    icon: '/versioncontrol.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>

      <body>
        <Header />

        <div className="flex p-6 gap-8 h-[calc(100vh-theme(spacing.20))] overflow-hidden">
          <Nav className="hidden md:block flex-shrink-0 w-65 pr-4 overflow-y-auto custom-scrollbar" />

          <div className="flex-1 min-w-0 pr-4 overflow-y-auto custom-scrollbar">
            {children}
          </div>

          <Contents className="hidden lg:block flex-shrink-0 w-40 overflow-y-auto custom-scrollbar" />
        </div>
      </body>
    </html>
  );
}
