
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'

import Header from "../components/Header/Header";
import Nav from "../components/Nav/Nav"
import Contents from "../components/Contents/Contents"


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Isaiah's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>

      <body>
        <Header />

        <div className="flex justify-center items-start min-h-screen">
          <Nav />

          <Contents />
        </div>

        {children}
      </body>
    </html>
  );
}
